# Generated by Django 3.2.18 on 2023-06-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_urls',
            field=models.TextField(blank=True, null=True),
        ),
    ]
