# Generated by Django 3.2.18 on 2023-06-01 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_anonymous_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='anonymous_username',
        ),
    ]
