# Generated by Django 3.2.18 on 2023-05-31 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posttrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttrack',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posttrack',
            name='image',
            field=models.ImageField(upload_to='post_track_images'),
        ),
    ]
