# Generated by Django 3.2.18 on 2023-06-01 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_anonymouscomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnonymousComment',
        ),
    ]
