# Generated by Django 3.2.18 on 2023-06-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='words',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
