# Generated by Django 3.2.18 on 2023-06-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='report',
        ),
        migrations.AddField(
            model_name='user',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
