# Generated by Django 3.2.18 on 2023-06-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='anonymous_username',
            field=models.CharField(default=1, max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
