# Generated by Django 3.2.18 on 2023-05-30 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='image_url',
        ),
        migrations.AddField(
            model_name='track',
            name='image',
            field=models.ImageField(default=1, upload_to='track_images'),
            preserve_default=False,
        ),
    ]
