# Generated by Django 3.2.18 on 2023-05-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
