# Generated by Django 3.2.18 on 2023-06-01 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_anonymous_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='anonymous_username',
        ),
    ]
