# Generated by Django 3.2.18 on 2023-06-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_anonymous_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='introductions',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
