# Generated by Django 3.2.18 on 2023-05-28 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_track_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='is_selected',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_by', to='accounts.track'),
        ),
    ]
