# Generated by Django 3.2.18 on 2023-05-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_track_is_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='image',
            field=models.ImageField(default=1, upload_to='track_images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='track',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
