# Generated by Django 3.2.18 on 2023-05-29 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20230529_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='image',
        ),
    ]
