# Generated by Django 3.2.18 on 2023-05-29 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_track_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='image_url',
        ),
    ]
