# Generated by Django 3.2.18 on 2023-05-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_track_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='image',
            field=models.ImageField(default=1, upload_to='track_images'),
            preserve_default=False,
        ),
    ]
