# Generated by Django 3.2.18 on 2023-05-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_track_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='image_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
