# Generated by Django 3.2.18 on 2023-05-29 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_track_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='image_url',
        ),
    ]
