# Generated by Django 3.2.18 on 2023-05-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balances', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.RemoveField(
            model_name='question',
            name='content1_users',
        ),
        migrations.RemoveField(
            model_name='result',
            name='category',
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='result',
            name='chosen_result',
            field=models.JSONField(default=list),
        ),
    ]
