# Generated by Django 3.2.18 on 2023-06-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='word1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='word2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
