# Generated by Django 3.2.18 on 2023-05-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balances', '0002_auto_20230526_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='category',
        ),
        migrations.AlterField(
            model_name='result',
            name='chosen_result',
            field=models.JSONField(default=list),
        ),
    ]
