# Generated by Django 3.2.18 on 2023-05-29 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balances', '0003_auto_20230526_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='content1_users',
        ),
    ]
